services:
  postgresql_database:
    image: postgres:16.2-alpine3.19
    container_name: postgresql_database
    restart: always
    environment:
      POSTGRES_DB: pixelated-project
      POSTGRES_PASSWORD: change-me-in-prod
      POSTGRES_USER: developer
    networks:
      - database_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  pixelated_pipeline:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    container_name: pixelated_pipeline
    restart: always
    networks:
      - proxy_network
      - database_network
    depends_on:
      - postgresql_database
    volumes:
      - './backend:/app' # In production comment this

  adminer:
    image: adminer
    container_name: adminer_database_ui
    restart: always
    networks:
      - database_network
    depends_on:
      - postgresql_database
    ports:
      - '9000:8080'

  pixelated_pen:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    container_name: pixelated_pen
    restart: always
    networks:
      - proxy_network
    # Don't know why but exposing this port makes HMR auto reload the output, making it like native HMR
    # without this, though the rebuild happens, we need to manually reload the webpage in the browser.
    # This can be removed in production as for production build, there is no HMR, but while developing
    # locally, do not remove this port mapping.
    ports:
      - '3000:3000' # In production comment this
    volumes:
      - "./frontend/src:/app/src" # In production comment this 
      - "./frontend/static:/app/static" # In production comment this
      - "./frontend/index.html:/app/index.html" # In production comment this
    depends_on:
      - pixelated_pipeline

  nginx:
    image: nginx:1.25.5-alpine
    restart: always
    container_name: reverse_proxy
    ports:
      # port mappings do not work with host network driver
      - '8080:80'
    networks:
      - proxy_network
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - pixelated_pipeline
      - pixelated_pen

volumes:
  postgres_volume:
    name: pixelated-project-data
    driver: local

networks:
  proxy_network:
    # https://docs.docker.com/network/drivers/host/ 
    # https://stackoverflow.com/questions/56582446/how-to-use-host-network-for-docker-compose
    # host driver is only available on linux and on docker desktop beta, so not working on windows
    # driver: host
    driver: bridge

  database_network:
    driver: bridge
