name: Publish Server Stub (Spring) to GitHub Packages And Put Docs to Remote Repository

on:
  workflow_call:
  workflow_dispatch:

env:
  DS_PKG_VER:
  SERVER_MAVEN_DEPS_HASH:

jobs:
  publish-server-stub:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    # Run GitHub Actions locally using Act - https://nektosact.com/introduction.html
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Package Version
        id: GetPackageVersion
        shell: bash
        run: echo "DS_PKG_VER=$(npm run --silent get-version)" >> "$GITHUB_ENV"

      - name: Setup OpenAPI
        uses: ./.github/actions/openapi-compile

      - name: Generate Server Stub
        shell: bash
        run: npm run openapi:generate-server

      - name: Hash Dependencies
        shell: bash
        run: |
          echo "SERVER_MAVEN_DEPS_HASH=$(node ./scripts/hash-server-maven-deps.js ./build/server/spring/pom.xml)" >> "$GITHUB_ENV"

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ env.SERVER_MAVEN_DEPS_HASH }}

      - name: Generate Server Documentation
        working-directory: ./build/server/spring
        shell: pwsh
        run: mvn javadoc:javadoc

      - name: Push Server Stub Docs To Repository
        uses: ./.github/actions/copy-docs
        with:
          commit-version: "$DS_PKG_VER"
          commit-message: updated server stub docs version
          source-directory: ./build/server/spring/target/site/apidocs
          target-repository: adityamayukhsom/devstream-docs
          target-directory: server
          target-branch: main
          bot-token: ${{ secrets.DEVSTREAM_DOCS_PAT }}

      - name: Generate OpenAPI Docs
        run: npm run openapi:docs

      - name: Push API Docs To Repository
        uses: ./.github/actions/copy-docs
        with:
          commit-version: "$DS_PKG_VER"
          commit-message: updated swagger api docs version
          source-directory: ./build/docs
          target-repository: adityamayukhsom/devstream-docs
          target-directory: swagger
          target-branch: main
          bot-token: ${{ secrets.DEVSTREAM_DOCS_PAT }}

      - name: Publish to GitHub Packages
        shell: pwsh
        working-directory: ./build/server/spring
        run: mvn deploy -D altDeploymentRepository=github::default::https://maven.pkg.github.com/AdityaMayukhSom/devstream-openapi -Darguments="-Dmaven.javadoc.skip=true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
