name: Publish Client Stub (TypeScript Fetch) to GitHub Packages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish-client-stub:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    # Run GitHub Actions locally using Act - https://nektosact.com/introduction.html
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OpenAPI
        uses: ./.github/actions/openapi-compile

      - name: Generate Client Stub
        run: npm run openapi:generate-client

      - name: Hash Dependencies
        run: |
          echo "PACKAGE_VERSION=$(npm run -s get-version)" >> $GITHUB_ENV
          echo "CLIENT_NODE_DEPS_HASH=$(node ./scripts/hash-node-deps.js ./build/client/typescript/package.json)" >> $GITHUB_ENV

      - name: Cache TypeScript Client Dependencies
        uses: actions/cache@v3
        with:
          path: ./build/client/typescript/node_modules
          key: ${{ runner.os }}-tsclient-${{ env.CLIENT_NODE_DEPS_HASH }}

      - name: Install TypeScript as devDependency & Compiles TS stubs into JS as mentioned in prepare script
        working-directory: ./build/client/typescript
        run: npm install

      - name: Generate Client Stub Docs
        run: npm run openapi:client-docs

      - name: Push Client Stub Docs To Repository
        uses: ./.github/actions/copy-docs
        with:
          commit-message: "updated client stub docs version to ${{ env.PACKAGE_VERSION }}"
          source-directory: ./build/client/typescript/docs/.vitepress/dist
          target-repository: adityamayukhsom/devstream-docs
          target-directory: client
          target-branch: main
          bot-token: ${{ secrets.DEVSTREAM_DOCS_PAT }}

      # Publish the package to GitHub Packages
      - name: Publish to GitHub Packages
        working-directory: ./build/client/typescript
        run: npm publish --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
